version: '2'

services:

  frontend:
    build: ./frontend
    volumes:
    - ./frontend:/frontend
    ports:
      - "3000:3000"
    networks:
      - react-django

  backend:
    build: ./backend
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
    networks:
      - react-django
    
  db:
    image: postgres:13
    ports:
      - "5432:5432"    
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypassword
    networks:
      - react-django

networks:
  react-django:
