version: '2'

services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - react-django

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - react-django

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8888:80'
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    depends_on:
        - mysql
    networks:
      - react-django

  mysql:
    image: mysql:5.7
    ports:
      - '3306:80'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=django
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - react-django

networks:
  react-django:
