version: '2'

services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/code
    networks:
      - react-django

  backend:
    build: ./backend
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app/code
    networks:
      - react-django
    
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: meio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 250303
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - react-django

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: gcgabriel257@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 250303
    networks:
      - react-django

networks:
  react-django:
