# Generated by Django 4.2.5 on 2023-09-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
