# Generated by Django 4.2 on 2023-10-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_user_userprofile_delete_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.CharField(default='Valor Padrão', max_length=255, verbose_name='user'),
        ),
    ]
