# Generated by Django 4.2 on 2023-10-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_produto_imagem_comentario_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='avaliacoes',
            field=models.ManyToManyField(related_name='produtos_avaliados', to='project.avaliacao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='comentarios',
            field=models.ManyToManyField(related_name='produtos_comentados', to='project.comentario'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagens',
            field=models.ManyToManyField(related_name='produtos_imagens', to='project.imagem'),
        ),
    ]
