# Generated by Django 4.2 on 2023-10-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_avaliacao_produto_remove_comentario_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.TextField(),
        ),
    ]
